In [ ]:
#NAME-VIPUL REDDY
#REG NO-20BEC1132

In [1]:
#1
Name="Vipul Reddy"
print(Name)

Vipul Reddy


In [2]:
Age=20
print(Age)

20


In [5]:
#2
X="Datascience is used to extract meaningful insights."
l=X.split(" ")
l

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

In [2]:
#3
def mult(a,b):
    return a*b
mult(9,7)

63

In [3]:
states={"Telangana":"Hyderabad","Bihar":"Patna","west bengal":"Kolkotta","Rajasthan":"Jaipur","Karnataka":"Banglore"}
states

{'Telangana': 'Hyderabad',
 'Bihar': 'Patna',
 'west bengal': 'Kolkotta',
 'Rajasthan': 'Jaipur',
 'Karnataka': 'Banglore'}

In [9]:
#5
l=list(range(0,1001))

In [6]:
import numpy as np

In [7]:
#6
m=np.identity(4)

In [8]:
m

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
#7
n=np.arange(1,10).reshape(3,3)

In [10]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#8
a=np.array([[5,9,8],[8,3,7]])
b=np.array([[9,1,9],[3,5,1]])
c=a+b
print(c)

[[14 10 17]
 [11  8  8]]


In [12]:
import datetime
import pandas as pd



In [13]:
#9
test_date = datetime.datetime.strptime("01-2-2023", "%d-%m-%Y")
K = 28
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))



Index(['01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023', '05-02-2023',
       '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023', '10-02-2023',
       '11-02-2023', '12-02-2023', '13-02-2023', '14-02-2023', '15-02-2023',
       '16-02-2023', '17-02-2023', '18-02-2023', '19-02-2023', '20-02-2023',
       '21-02-2023', '22-02-2023', '23-02-2023', '24-02-2023', '25-02-2023',
       '26-02-2023', '27-02-2023', '28-02-2023'],
      dtype='object')


In [14]:
#10
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
d=pd.DataFrame.from_dict(dictionary)
d

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240